name: Tests
on: [push]
jobs:
  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v2
      - shell: python
        run: |
          from pathlib import Path
          print(Path("relative").resolve())
          import pathlib
          print(pathlib._getfinalpathname)
