name: Tests
on: [push]
jobs:
  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v2
      - shell: python
        run: |
          import pathlib
          print(pathlib._getfinalpathname("relative"))
