name: Tests
on: [push]
jobs:
  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v2
      - shell: python
        run: |
          import os.path
          import pathlib
          s = "relative"
          s, tail = os.path.split(s)
          print(s)
          print(pathlib._getfinalpathname(s))
