name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ["true"]
        experimental: [false]
        include:
          - command: "false"
            experimental: true
    steps:
      - run: ${{ matrix.command }}
        continue-on-error: ${{ matrix.experimental }}
